/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as Sqlv2RouteImport } from './routes/sqlv2'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsExecutionhistoryRouteImport } from './routes/jobs.executionhistory'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as JobsAgentNewRouteImport } from './routes/jobs.agent.new'
import { Route as JobsJobIdEditRouteImport } from './routes/jobs.$jobId.edit'

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const Sqlv2Route = Sqlv2RouteImport.update({
  id: '/sqlv2',
  path: '/sqlv2',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JobsRoute,
} as any)
const JobsExecutionhistoryRoute = JobsExecutionhistoryRouteImport.update({
  id: '/executionhistory',
  path: '/executionhistory',
  getParentRoute: () => JobsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const JobsAgentNewRoute = JobsAgentNewRouteImport.update({
  id: '/agent/new',
  path: '/agent/new',
  getParentRoute: () => JobsRoute,
} as any)
const JobsJobIdEditRoute = JobsJobIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => JobsJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/logs': typeof LogsRoute
  '/sql': typeof SqlRoute
  '/sqlv2': typeof Sqlv2Route
  '/storage': typeof StorageRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/executionhistory': typeof JobsExecutionhistoryRoute
  '/jobs/new': typeof JobsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/jobs/agent/new': typeof JobsAgentNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/sql': typeof SqlRoute
  '/sqlv2': typeof Sqlv2Route
  '/storage': typeof StorageRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/executionhistory': typeof JobsExecutionhistoryRoute
  '/jobs/new': typeof JobsNewRoute
  '/admin': typeof AdminIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/jobs/agent/new': typeof JobsAgentNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/logs': typeof LogsRoute
  '/sql': typeof SqlRoute
  '/sqlv2': typeof Sqlv2Route
  '/storage': typeof StorageRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/executionhistory': typeof JobsExecutionhistoryRoute
  '/jobs/new': typeof JobsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/jobs/agent/new': typeof JobsAgentNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/dashboard'
    | '/jobs'
    | '/logs'
    | '/sql'
    | '/sqlv2'
    | '/storage'
    | '/admin/logs'
    | '/admin/users'
    | '/jobs/$jobId'
    | '/jobs/executionhistory'
    | '/jobs/new'
    | '/admin/'
    | '/jobs/'
    | '/jobs/$jobId/edit'
    | '/jobs/agent/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/logs'
    | '/sql'
    | '/sqlv2'
    | '/storage'
    | '/admin/logs'
    | '/admin/users'
    | '/jobs/$jobId'
    | '/jobs/executionhistory'
    | '/jobs/new'
    | '/admin'
    | '/jobs'
    | '/jobs/$jobId/edit'
    | '/jobs/agent/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/dashboard'
    | '/jobs'
    | '/logs'
    | '/sql'
    | '/sqlv2'
    | '/storage'
    | '/admin/logs'
    | '/admin/users'
    | '/jobs/$jobId'
    | '/jobs/executionhistory'
    | '/jobs/new'
    | '/admin/'
    | '/jobs/'
    | '/jobs/$jobId/edit'
    | '/jobs/agent/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRouteWithChildren
  LogsRoute: typeof LogsRoute
  SqlRoute: typeof SqlRoute
  Sqlv2Route: typeof Sqlv2Route
  StorageRoute: typeof StorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sqlv2': {
      id: '/sqlv2'
      path: '/sqlv2'
      fullPath: '/sqlv2'
      preLoaderRoute: typeof Sqlv2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/executionhistory': {
      id: '/jobs/executionhistory'
      path: '/executionhistory'
      fullPath: '/jobs/executionhistory'
      preLoaderRoute: typeof JobsExecutionhistoryRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jobs/agent/new': {
      id: '/jobs/agent/new'
      path: '/agent/new'
      fullPath: '/jobs/agent/new'
      preLoaderRoute: typeof JobsAgentNewRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$jobId/edit': {
      id: '/jobs/$jobId/edit'
      path: '/edit'
      fullPath: '/jobs/$jobId/edit'
      preLoaderRoute: typeof JobsJobIdEditRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLogsRoute: typeof AdminLogsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLogsRoute: AdminLogsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JobsJobIdRouteChildren {
  JobsJobIdEditRoute: typeof JobsJobIdEditRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdEditRoute: JobsJobIdEditRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  JobsExecutionhistoryRoute: typeof JobsExecutionhistoryRoute
  JobsNewRoute: typeof JobsNewRoute
  JobsIndexRoute: typeof JobsIndexRoute
  JobsAgentNewRoute: typeof JobsAgentNewRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsExecutionhistoryRoute: JobsExecutionhistoryRoute,
  JobsNewRoute: JobsNewRoute,
  JobsIndexRoute: JobsIndexRoute,
  JobsAgentNewRoute: JobsAgentNewRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRouteWithChildren,
  LogsRoute: LogsRoute,
  SqlRoute: SqlRoute,
  Sqlv2Route: Sqlv2Route,
  StorageRoute: StorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
